server:
  port: ${server-port} #9090


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${url} #jdbc:postgresql://localhost:5432/commentAppDb
    username: ${user} #postgres
    password: ${password} #root

  jpa:
      hibernate:
        ddl-auto: update
        format_sql: true
      show-sql: true



